---
- name: Deploy Kubernetes cluster on Hetzner Cloud
  hosts: kubernetes
  become: yes
  gather_facts: yes
  
  pre_tasks:
    - name: Wait for system to be ready
      wait_for_connection:
        timeout: 300
        
    - name: Gather facts
      setup:

  roles:
    - common

- name: Initialize Kubernetes control plane
  hosts: control_plane
  become: yes
  roles:
    - kubernetes-master

- name: Join worker nodes to cluster
  hosts: workers
  become: yes
  roles:
    - kubernetes-worker